### ISSUE TITLE
SASL mechs not working

### ISSUE THREAD

**Issue by peterforeman** [ServerContainers/mail-gateway#5]
I'm trying to use the mail-gateway for sending through Amazon SES. Unfortunately the basic container does not include the correct mechanisms for SASL2.

Request: add debian package "libsasl2-modules" to Dockerfile so that the correct SASL2 mechs are installed.

```
Apr  7 12:16:57 779f6c28bfa9 postfix/smtp[249]: warning: SASL authentication failure: No worthy mechs found
Apr  7 12:16:58 779f6c28bfa9 postfix/smtp[249]: B46951A4DB1F8: SASL authentication failed; cannot authenticate to server email-smtp.eu-central-1.amazonaws.com[3.125.101.56]: no mechanism available

```

**Comment by MarvAmBass** [comment]
I Peter,

thanks I've added the module :) hope this fixes your problem :)
